### PR TITLE
Fix `Id` clash when using multiple `Tree`s 

### LINKED ISSUE #11: Bug `v0.2.0`: Id clash when using multiple `Tree`s
With the release of `v0.2.0`, it is not longer possible to create multiple `Tree`s within a single frame, as this results in id clashes. With `v0.1.0` this wasn't an issue.

In the specific case I'm having, I have three `Tabbed` containers, the id clash `egui` gives me is on the first `Tab` button of each `Tree` `Container`.

### PR DESCRIPTION
**Pull request by emilk**
* Closes #11 

* (this is a fork of https://github.com/rerun-io/egui_tiles/pull/12)

---

Each `Tree` now has a globally unique id, meaning the same `Tree` can be rendered in different `Ui`:s and still work, and you can have multiple trees. However, it is up to the user to pick a globally unique id.

### CODE REVIEW

File: src/tree.rs [hunk 1]
```diff
@@ -33,16 +33,9 @@ pub struct Tree<Pane> {
...
 
-impl<Pane> Default for Tree<Pane> {
-    // An empty tree
-    fn default() -> Self {
-        Self {
-            root: None,
-            tiles: Default::default(),
-        }
-    }
+    /// The previous id used to draw the tree.
```
Comment (tosti007) [inline src/tree.rs:37]: This doc comment should be changed to better show that it's a fixed value. When working on this I initially had this value be updated each draw call.

**Review by tosti007 — APPROVED** [review]
